// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VTr69DOkNNegKY87YRGg3Dd1xz6AXw0',
    appId: '1:240557146007:android:f502c241b1b35d239d0ed2',
    messagingSenderId: '240557146007',
    projectId: 'text-markt-7c6f4',
    storageBucket: 'text-markt-7c6f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKcOrQvNwVXCvUGJXmsOyQvLjGd4lACM',
    appId: '1:240557146007:ios:e8d0cf1dfe5d88409d0ed2',
    messagingSenderId: '240557146007',
    projectId: 'text-markt-7c6f4',
    storageBucket: 'text-markt-7c6f4.firebasestorage.app',
    iosBundleId: 'com.example.textMarkt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-mmlqt_P_PfqnsmVrokRgcCkmjicjtQ',
    appId: '1:240557146007:web:c0fed688d58edb319d0ed2',
    messagingSenderId: '240557146007',
    projectId: 'text-markt-7c6f4',
    authDomain: 'text-markt-7c6f4.firebaseapp.com',
    storageBucket: 'text-markt-7c6f4.firebasestorage.app',
    measurementId: 'G-K1JHCPNLWR',
  );
}